import type { Metadata } from "next";
import { notFound } from "next/navigation";

type Slug="construction-os"|"manufacturing-os"|"distribution-os"|"logistics-os"|"property-management-os";
const data={
  "construction-os":{name:"Construction OS",keyword:"construction management software",alt:"construction CRM",intro:"One system for leads, estimates, projects, sites, crews, subcontractors, documents, costs and progress.",modules:["Construction CRM","Estimating & quotations","Site management","Crew & subcontractor control","Daily reports","Documents & approvals","Budget vs actual","Client portal"]},
  "manufacturing-os":{name:"Manufacturing OS",keyword:"manufacturing operations software",alt:"custom manufacturing ERP",intro:"Connect orders, planning, production, inventory, quality and delivery in one operational system.",modules:["Sales orders","Production planning","Bill of materials","Inventory","Quality control","Maintenance","Purchasing","Delivery reporting"]},
  "distribution-os":{name:"Distribution OS",keyword:"distribution management software",alt:"wholesale CRM and ERP",intro:"Manage customers, pricing, purchasing, stock, fulfilment and margins with live operational data.",modules:["Customer management","Pricing rules","Purchasing","Warehouse","Order fulfilment","Inventory control","Delivery","Margin reporting"]},
  "logistics-os":{name:"Logistics OS",keyword:"logistics management software",alt:"custom logistics CRM",intro:"Coordinate orders, dispatch, vehicles, drivers, documents and customer communication without manual handoffs.",modules:["Order intake","Dispatch","Fleet","Driver activity","Route workflows","Proof of delivery","Customer updates","Performance dashboards"]},
  "property-management-os":{name:"Property Management OS",keyword:"property management software",alt:"custom property CRM",intro:"Control properties, tenants, contracts, maintenance, suppliers, payments and owner reporting.",modules:["Property CRM","Tenant management","Contracts","Maintenance","Supplier workflows","Payments","Document automation","Owner dashboards"]},
} satisfies Record<Slug,{name:string;keyword:string;alt:string;intro:string;modules:string[]}>;
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const s=data[slug as Slug];if(!s)return{};return{title:`${s.name} | Custom ${s.keyword} | NORTH/OS`,description:`${s.intro} Modular industry Business Operating System from €15,000.`,keywords:[s.keyword,s.alt,"business operating system","workflow automation","custom business software"],alternates:{canonical:`/solutions/${slug}`}};}
export default async function SolutionPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=data[slug as Slug];if(!s)notFound();return <main><nav className="topbar wrap"><a className="logo" href="/"><span>N</span>NORTH<i>/OS</i></a><div className="navlinks"><a href="/#platform">Platform</a><a href="/#packages">Packages</a><a href="/#solutions">All solutions</a></div><a className="navbutton" href="/#contact">Configure your system <b>↗</b></a></nav><section className="solution-hero wrap"><div className="overline"><span/> INDUSTRY BUSINESS OPERATING SYSTEM</div><h1>{s.name}:<br/><em>your operation, connected.</em></h1><p>{s.intro}</p><div className="hero-actions"><a className="btn blue" href="/#contact">Discuss your workflow <b>↗</b></a><span>Advanced implementations from €15,000</span></div></section><section className="solution-modules"><div className="wrap"><div><div className="section-label">INDUSTRY MODULES</div><h2>Built on one proven<br/><em>operating core.</em></h2><p>Every {s.name} starts with NORTH/OS Core and adds the workflows, data and integrations specific to your company.</p></div><div className="module-grid">{s.modules.map((m,i)=><article key={m}><span>0{i+1}</span><b>{m}</b><i>✓</i></article>)}</div></div></section><section className="market-cta"><div className="wrap"><div><div className="section-label">COMMERCIAL ASSESSMENT</div><h2>See how {s.name} fits your business.</h2><p>Map the systems, spreadsheets and manual processes your company needs to replace.</p></div><a className="btn blue" href="/#contact">Request system plan <b>↗</b></a></div></section><footer><div className="wrap footer-bottom"><span>© 2026 NORTH/OS</span><span>Premium Business Automation Studio</span><a href="/">Main website ↗</a></div></footer></main>}
