import type { Metadata } from "next";
import { notFound } from "next/navigation";

type Slug="construction-os"|"manufacturing-os"|"distribution-os"|"logistics-os"|"property-management-os";
const data={
  "construction-os":{name:"Construction OS",keyword:"construction management software",intro:"Connect leads, estimates, sites, crews, subcontractors, documents, costs and progress in one system.",modules:["Construction CRM","Estimates & quotations","Projects & sites","Crews & subcontractors","Daily reports","Documents & approvals","Cost control","Client dashboards"]},
  "manufacturing-os":{name:"Manufacturing OS",keyword:"manufacturing operations software",intro:"Connect orders, planning, production, inventory, quality and delivery in one operational flow.",modules:["Customer orders","Production planning","Bill of materials","Inventory","Quality control","Maintenance","Purchasing","Performance dashboards"]},
  "distribution-os":{name:"Distribution OS",keyword:"distribution management software",intro:"Manage customers, purchasing, pricing, stock, fulfilment and margins with live operational data.",modules:["Customer management","Pricing rules","Purchasing","Warehouse","Order fulfilment","Inventory control","Delivery","Margin reporting"]},
  "logistics-os":{name:"Logistics OS",keyword:"logistics management software",intro:"Coordinate orders, dispatch, vehicles, drivers, documents and customer communication without manual handoffs.",modules:["Order intake","Dispatch","Fleet","Driver activity","Route workflows","Proof of delivery","Customer updates","Operations dashboards"]},
  "property-management-os":{name:"Property Management OS",keyword:"property management software",intro:"Control properties, tenants, contracts, maintenance, suppliers, payments and owner reporting.",modules:["Property CRM","Tenant management","Contracts","Maintenance","Supplier workflows","Payments","Document automation","Owner dashboards"]},
} satisfies Record<Slug,{name:string;keyword:string;intro:string;modules:string[]}>;
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const s=data[slug as Slug];if(!s)return{};return{title:`${s.name} | Custom ${s.keyword}`,description:`${s.intro} Built on the NORTH/OS Business Operating System Core.`,keywords:[s.keyword,"business operating system","workflow automation","custom business software"],alternates:{canonical:`/solutions/${slug}`}};}
export default async function SolutionPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=data[slug as Slug];if(!s)notFound();return <main className="locale-page"><nav className="nav shell"><a className="brand" href="/"><span className="brand-mark">N</span>NORTH<span>/OS</span></a><div className="locale-nav"><a href="/#platform">Platform</a><a href="/#solutions">Industries</a><a href="/#process">Process</a></div><a className="nav-cta" href="/#contact">Book a strategy call <span>↗</span></a></nav><section className="locale-hero shell"><div className="eyebrow"><i/> INDUSTRY BUSINESS OPERATING SYSTEM</div><h1>{s.name}.<br/><em>Your operation, connected.</em></h1><p>{s.intro} The same proven operating core, configured around the way your company actually works.</p><div className="actions"><a className="button primary" href="/#contact">Discuss your workflow <span>↗</span></a><a className="button ghost" href="/#solutions">All industries <span>↓</span></a></div><div className="locale-orbit" aria-hidden="true"><b>CRM</b><b>OPS</b><b>DATA</b><b>AI</b><i>{s.name.split(" ")[0].toUpperCase()}<br/>OS</i></div></section><section className="locale-proof"><div className="shell"><div className="kicker">INDUSTRY SOLUTION</div><h2>One reliable source of <em>operational truth.</em></h2><p>Replace spreadsheets, duplicated entry and disconnected point solutions with workflows that connect commercial, operational and management teams.</p></div></section><section className="locale-services shell"><div><div className="kicker">WHAT IT CAN INCLUDE</div><h2>Configured around<br/><em>your workflow.</em></h2></div><div>{s.modules.map((x,i)=><article key={x}><span>0{i+1}</span><b>{x}</b><i>✓</i></article>)}</div></section><section className="locale-cta"><div className="shell"><h2>See how {s.name} fits your business.</h2><p>Map the manual processes and disconnected systems your operation needs to replace.</p><a className="button primary" href="/#contact">Book a strategy call <span>↗</span></a></div></section><footer><div className="shell footer-bottom"><span>© 2026 NORTH/OS</span><span>Premium Business Automation Studio</span><a href="/">Main website ↗</a></div></footer></main>}
