import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Business Operating System & Automation Software | NORTH/OS",
  description: "A modular Business Operating System for growing companies. Replace disconnected software, Excel and manual work with one custom platform. Packages from €5,000.",
  keywords: ["business operating system","business automation software","custom business software","custom CRM development","workflow automation","business process automation","AI business automation","custom ERP","operations management software"],
};

const packages = [
  { name:"CORE", price:"€5,000", line:"Your essential operating layer", lead:"Replace scattered tools with one secure system for customers, work, people and reporting.", features:["Custom CRM","Customer Management","Projects","Tasks","Employees","Roles & Permissions","Dashboard","Documents","Calendar","Notifications","Reporting","Basic API","Basic Branding"], note:"Fast implementation" },
  { name:"AUTOMATION", price:"€8,000", line:"Your business, running automatically", lead:"Connect teams and remove repetitive work with intelligent workflows across your company.", features:["Everything in Core","Business Workflow Automation","Email Automation","WhatsApp Integration","Telegram Integration","Google Workspace","Microsoft 365","Electronic Signatures","Document Automation","Approval Workflows","Advanced Reporting","OpenAI Integration","Custom Business Logic"], note:"Most popular", featured:true },
  { name:"ADVANCED", price:"€15,000", line:"A complete industry operating system", lead:"Build your competitive advantage with deep operational modules and enterprise architecture.", features:["Everything in Automation","Industry Specific Modules","Advanced Integrations","ERP & Accounting Connections","Inventory & Production","Logistics Modules","Construction Modules","Property Management Modules","Manufacturing Modules","Custom Dashboards","AI Agents","Enterprise Security","Multi-company Support","Unlimited Customization"], note:"Enterprise ready" },
];

const industries = [
  {n:"01",title:"Construction OS",slug:"construction-os",text:"Control leads, estimates, sites, crews, subcontractors, documents, costs and progress from one platform.",tags:["Construction CRM","Sites","Cost control"]},
  {n:"02",title:"Manufacturing OS",slug:"manufacturing-os",text:"Connect orders, planning, production, inventory, quality and delivery in one operational flow.",tags:["Production","Inventory","Quality"]},
  {n:"03",title:"Distribution OS",slug:"distribution-os",text:"Run customers, purchasing, stock, pricing, fulfilment and margins with real-time visibility.",tags:["Wholesale","Warehouse","Sales"]},
  {n:"04",title:"Logistics OS",slug:"logistics-os",text:"Coordinate orders, dispatch, vehicles, drivers, documents and customer communication without manual handoffs.",tags:["Dispatch","Fleet","Tracking"]},
  {n:"05",title:"Property Management OS",slug:"property-management-os",text:"Manage properties, tenants, contracts, maintenance, suppliers, payments and owner reporting.",tags:["Properties","Tenants","Finance"]},
];

const faq = [
  ["What is a Business Operating System?","A Business Operating System is one connected software platform for managing customers, work, employees, documents, finance, reporting and automation. Unlike a collection of generic tools, NORTH/OS is configured around the way your company actually operates."],
  ["How is this different from a CRM or ERP?","A CRM focuses mainly on sales and an ERP on resource planning. NORTH/OS connects both with projects, tasks, people, documents, approvals, communication, analytics and AI—without forcing you into a rigid off-the-shelf workflow."],
  ["What does a project cost?","Core starts from €5,000, Automation from €8,000 and Advanced from €15,000. Final investment depends on modules, integrations, data migration and business complexity. You receive a fixed implementation scope before work begins."],
  ["How quickly can Core be implemented?","A focused Core implementation can be ready in a short timeframe once workflows, data and decision-makers are available. More complex Automation and Advanced deployments are delivered in controlled stages."],
  ["Can NORTH/OS connect to our existing software?","Yes. We connect Google Workspace, Microsoft 365, WhatsApp, Telegram, accounting platforms, ERPs, advertising tools, databases and virtually any system with an API."],
  ["Do we own our system and data?","Yes. Your company controls its business data and receives the ownership rights defined in the implementation agreement. NORTH/OS is built to remove platform dependency, not create more of it."],
];

const insights = [
  ["Business Operating System","When growing companies need more than CRM and ERP"],
  ["Construction Software","How a Construction OS connects sales, sites and cost control"],
  ["Workflow Automation","12 business processes to automate before hiring more administration"],
  ["Custom CRM Development","Custom CRM vs HubSpot: the decision framework for complex sales"],
  ["AI Business Automation","Where AI agents create measurable operational value"],
  ["Custom ERP","When custom ERP becomes the lower-risk business decision"],
];

export default function Home(){
  const schema = {"@context":"https://schema.org","@graph":[
    {"@type":"Organization","@id":"https://webesign.vercel.app/#organization","name":"NORTH/OS","url":"https://webesign.vercel.app/","description":"Premium Business Automation Studio providing modular Business Operating Systems for growing companies.","areaServed":["Netherlands","Denmark","Norway","Sweden","Ireland"]},
    {"@type":"SoftwareApplication","@id":"https://webesign.vercel.app/#product","name":"NORTH/OS Business Operating System","applicationCategory":"BusinessApplication","operatingSystem":"Web","offers":[{"@type":"Offer","name":"Core","price":"5000","priceCurrency":"EUR"},{"@type":"Offer","name":"Automation","price":"8000","priceCurrency":"EUR"},{"@type":"Offer","name":"Advanced","price":"15000","priceCurrency":"EUR"}]},
    {"@type":"FAQPage","mainEntity":faq.map(([q,a])=>({"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}}))}
  ]};
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <nav className="topbar wrap" aria-label="Main navigation">
      <a className="logo" href="#top"><span>N</span>NORTH<i>/OS</i></a>
      <div className="navlinks"><a href="#platform">Platform</a><a href="#packages">Packages</a><a href="#solutions">Solutions</a><a href="#faq">FAQ</a></div>
      <a className="navbutton" href="#contact">Configure your system <b>↗</b></a>
    </nav>

    <section className="hero wrap" id="top">
      <div className="hero-main">
        <div className="overline"><span/> THE BUSINESS OS FOR GROWING COMPANIES</div>
        <h1>One system<br/>to run your<br/><em>entire business.</em></h1>
        <p>NORTH/OS replaces disconnected software, Excel spreadsheets and manual work with one Business Operating System—configured around your company.</p>
        <div className="hero-actions"><a className="btn blue" href="#packages">Explore packages <b>↘</b></a><a className="btn outline" href="#contact">Book strategy call <b>↗</b></a></div>
        <div className="hero-facts"><span><b>€5,000</b><small>Starting investment</small></span><span><b>10–500+</b><small>Employee companies</small></span><span><b>100%</b><small>Built around your workflow</small></span></div>
      </div>
      <div className="product-stage" aria-label="NORTH OS platform interface preview">
        <div className="stage-top"><div><span className="stage-logo">N</span><b>Operations Control</b></div><span className="live"><i/> LIVE</span></div>
        <div className="stage-grid"><div className="stage-side"><small>WORKSPACE</small>{["Overview","Customers","Projects","Operations","Employees","Finance","Automations"].map((x,i)=><span className={i===0?"on":""} key={x}><i>{["⌂","◎","□","◇","♙","€","✦"][i]}</i>{x}</span>)}</div><div className="stage-content"><header><div><small>COMPANY OVERVIEW</small><h3>Friday, 7 August</h3></div><button>+ New workflow</button></header><div className="kpis"><article><small>Revenue</small><b>€482,680</b><span>↑ 12.4%</span></article><article><small>Active projects</small><b>38</b><span>92% on track</span></article><article><small>Team activity</small><b>1,248</b><span>↑ 18.2%</span></article></div><div className="stage-lower"><div className="revenue-card"><div><small>OPERATING PERFORMANCE</small><b>Revenue & margin</b></div><div className="visual-bars">{[42,55,48,66,61,74,70,85,80,96].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div><div className="axis"><span>MAR</span><span>APR</span><span>MAY</span><span>JUN</span><span>JUL</span><span>AUG</span></div></div><div className="workflow-card"><small>AUTOMATIONS TODAY</small>{[["New lead assigned","12:42"],["Invoice approved","11:18"],["Site report created","09:36"]].map(([x,t])=><div key={x}><i>✓</i><span><b>{x}</b><small>{t}</small></span></div>)}</div></div></div></div>
        <div className="stage-chip chip-one"><i>✦</i><span><b>AI workflow complete</b><small>Proposal prepared & sent</small></span></div><div className="stage-chip chip-two"><small>HOURS SAVED</small><b>42.6</b><span>this month</span></div>
      </div>
    </section>

    <section className="positioning" id="platform"><div className="wrap position-grid"><div><div className="section-label">THE PRODUCT</div><h2>Not another tool.<br/><em>Your operational core.</em></h2></div><div><p>Generic software makes your company adapt to someone else’s process. NORTH/OS starts with a proven Business Operating System Core, then configures the modules, rules and integrations around how your business creates value.</p><p>The result is one place to manage customers, work, people, data and decisions—with automation running across every department.</p></div></div><div className="wrap product-strip">{[["01","Commercial","Leads · CRM · Customers"],["02","Operations","Projects · Tasks · Delivery"],["03","People","Employees · Roles · Activity"],["04","Control","Finance · Reports · Documents"],["05","Intelligence","Automation · Analytics · AI"]].map(([n,a,b])=><article key={n}><span>{n}</span><b>{a}</b><small>{b}</small></article>)}</div></section>

    <section className="packages wrap" id="packages"><div className="section-heading"><div><div className="section-label">MODULAR PRODUCT STRATEGY</div><h2>Start with what you need.<br/><em>Expand without limits.</em></h2></div><p>Three clear implementation packages. One enterprise-grade platform underneath. No per-seat restrictions and no collection of disconnected subscriptions.</p></div><div className="package-grid">{packages.map(p=><article className={p.featured?"package featured":"package"} key={p.name}>{p.featured&&<div className="popular">RECOMMENDED</div>}<div className="package-head"><span>{p.name}</span><small>{p.note}</small><h3>Starting from <b>{p.price}</b></h3><p>{p.line}</p></div><div className="package-body"><p>{p.lead}</p><ul>{p.features.map(f=><li key={f}><i>✓</i>{f}</li>)}</ul></div><a href="#contact">Configure {p.name.toLowerCase()} <b>↗</b></a></article>)}</div><p className="pricing-note">Every implementation begins with a business-fit review. Final scope and fixed investment are confirmed before implementation.</p></section>

    <section className="solutions" id="solutions"><div className="wrap"><div className="section-heading light"><div><div className="section-label">INDUSTRY SOLUTIONS</div><h2>One proven core.<br/><em>Built for your industry.</em></h2></div><p>Each solution uses the same Business Operating System Core, then adapts workflows, data models and automation to your operation.</p></div><div className="solution-list">{industries.map(x=><a href={`/solutions/${x.slug}`} key={x.slug}><span>{x.n}</span><div><h3>{x.title}</h3><p>{x.text}</p><div>{x.tags.map(t=><i key={t}>{t}</i>)}</div></div><b>Explore solution ↗</b></a>)}</div></div></section>

    <section className="implementation wrap"><div className="section-heading"><div><div className="section-label">IMPLEMENTATION, NOT DEVELOPMENT HOURS</div><h2>A working system.<br/><em>Not an endless project.</em></h2></div><p>We provide a defined business outcome, a fixed implementation scope and a platform your team can use—not a timesheet.</p></div><div className="steps">{[["01","Model","We map processes, roles, data and measurable operational outcomes."],["02","Configure","We configure Core, selected modules, permissions and your business logic."],["03","Connect","We integrate existing software, migrate priority data and automate handoffs."],["04","Activate","We test real workflows, train your team and launch in controlled stages."],["05","Expand","Add modules, companies and intelligence as the operation grows."]].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>

    <section className="decision"><div className="wrap decision-grid"><div><div className="section-label">BUILT FOR DECISION-MAKERS</div><h2>Visibility for leadership.<br/><em>Clarity for every team.</em></h2><p>Designed for CEOs, Founders and Managing Directors who need the business to scale without adding administrative complexity.</p></div><div className="decision-metrics"><article><b>01</b><span><strong>Know what is happening</strong><small>Live commercial and operational performance.</small></span></article><article><b>02</b><span><strong>Know who owns the next action</strong><small>Clear responsibilities, approvals and deadlines.</small></span></article><article><b>03</b><span><strong>Know where margin is lost</strong><small>Connected revenue, delivery, cost and activity data.</small></span></article><article><b>04</b><span><strong>Scale without operational chaos</strong><small>Repeatable workflows and automation built in.</small></span></article></div></div></section>

    <section className="seo-hub wrap"><div className="section-heading"><div><div className="section-label">BUYER RESOURCES</div><h2>Make the right<br/><em>software decision.</em></h2></div><p>Commercial guidance for leadership teams evaluating business automation, custom CRM, operations software and ERP modernization.</p></div><div className="insight-grid">{insights.map(([tag,title],i)=><article key={title}><span>{tag}</span><h3>{title}</h3><a href="#contact">Discuss this with an architect ↗</a><small>0{i+1}</small></article>)}</div><div className="country-links"><span>Serving growing companies in</span><a href="/nl">Netherlands</a><a href="/da">Denmark</a><a href="/no">Norway</a><a href="/sv">Sweden</a><a href="/ie">Ireland</a></div></section>

    <section className="faq wrap" id="faq"><div className="faq-intro"><div className="section-label">FAQ</div><h2>Before you<br/><em>choose.</em></h2><p>Direct answers for leadership teams evaluating a new operational platform.</p></div><div>{faq.map(([q,a],i)=><details key={q} open={i===0}><summary><span>0{i+1}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></section>

    <section className="contact" id="contact"><div className="wrap contact-grid"><div><div className="section-label">CONFIGURE YOUR NORTH/OS</div><h2>What should your<br/><em>business run on?</em></h2><p>Tell us what you need to automate. We will recommend the right package, modules and implementation path.</p><div className="minimum"><small>MINIMUM IMPLEMENTATION</small><b>€5,000</b><span>Core · Fixed scope · Designed around your business</span></div></div><form><div className="form-title"><span>01</span><div><b>Business fit assessment</b><small>For companies ready to replace disconnected tools</small></div></div><div className="form-row"><label>Full Name<input name="name" placeholder="Your full name" required/></label><label>Company<input name="company" placeholder="Company name" required/></label></div><div className="form-row"><label>Business Email<input name="email" type="email" placeholder="you@company.com" required/></label><label>Company Website<input name="website" type="url" placeholder="https://company.com"/></label></div><div className="form-row"><label>Number of Employees<select name="employees" defaultValue="" required><option value="" disabled>Select company size</option><option>10–25</option><option>26–50</option><option>51–100</option><option>101–250</option><option>251–500</option><option>500+</option></select></label><label>Package<select name="package" defaultValue=""><option value="" disabled>Select a package</option><option>Core — from €5,000</option><option>Automation — from €8,000</option><option>Advanced — from €15,000</option><option>Help me choose</option></select></label></div><fieldset><legend>Priority modules</legend><div className="check-grid">{["CRM","Projects","Employees","Finance","Documents","Workflow automation","Integrations","Inventory","Industry modules","AI agents"].map(x=><label key={x}><input type="checkbox" name="modules" value={x}/><span>{x}</span></label>)}</div></fieldset><label>What would you like to automate?<textarea name="automation" rows={4} placeholder="Describe the manual work, disconnected systems or operational bottlenecks you want to replace." required/></label><button type="submit">Request your system plan <b>↗</b></button><small className="privacy">Projects start from €5,000. Your information is used only to assess business fit.</small></form></div></section>

    <footer><div className="wrap footer-main"><a className="logo" href="#top"><span>N</span>NORTH<i>/OS</i></a><p>Premium Business Automation Studio.<br/>One system for your entire operation.</p><div><a href="#platform">Platform</a><a href="#packages">Packages</a><a href="#solutions">Solutions</a><a href="#contact">Contact</a></div></div><div className="wrap footer-bottom"><span>© 2026 NORTH/OS</span><span>Netherlands · Denmark · Norway · Sweden · Ireland</span><span>Business systems, built differently.</span></div></footer>
  </main>
}
