import type { Metadata } from "next";
import Image from "next/image";
import Link from "../components/SafeLink";
import { Brand } from "../components/SiteHeader";
import { IconAlert, IconBox, IconChart, IconClipboard, IconCoins, IconKanban, IconLayers, IconMegaphone, IconRoute, IconScatter, IconShield, IconUsers } from "../components/Icons";
import ConstructionTracking from "./ConstructionTracking";
import WorkflowReviewForm from "./WorkflowReviewForm";
import "./construction.css";

export const metadata: Metadata = {
  title: "Construction Business Operating System",
  description: "Connect construction projects, teams, leads, tasks, costs and reporting in one custom operating system. Get a free workflow review.",
  alternates: { canonical: "/construction" },
  openGraph: { title: "One operating system for your construction business | OPSYNQ", description: "Replace spreadsheets, WhatsApp and disconnected tools with a system built around your workflow.", url: "/construction", images: ["/product/construction-dashboard.jpg"] },
};

const problems = [["Too many tools", "Projects, messages, spreadsheets and documents live in different places."], ["No real-time visibility", "You only discover delays, problems and missed tasks after they happen."], ["Constant follow-up", "Managers waste time asking teams for updates instead of managing the business."], ["Information gets lost", "Leads, tasks, costs and project updates disappear between systems and conversations."]];
const features = [["Leads & Sales", "Track enquiries, opportunities and follow-ups without losing potential work."], ["Projects", "See active projects, stages, deadlines and responsibilities from one dashboard."], ["Teams & Crews", "Know who is working where and what needs attention."], ["Tasks & Operations", "Assign work, track progress and keep important updates visible."], ["Costs & Performance", "Monitor costs, revenue and project performance."], ["Reports & Management", "Give management a real-time overview without chasing people for information."]];
const faqs = [["How much does an OPSYNQ system cost?", "Every implementation is different because OPSYNQ is built around the company's workflows and requirements. Typical custom implementations start from €5,000. We first identify the operational problem and define the right first version before discussing the final scope."], ["Is OPSYNQ a CRM?", "No. CRM can be part of the system, but OPSYNQ is designed as a broader Business Operating System connecting sales, projects, operations, teams and reporting."], ["Do we need to replace everything immediately?", "No. The system can start with one process and expand gradually."], ["Can OPSYNQ integrate with our existing tools?", "Yes. Integrations can be included depending on your existing software, available APIs and the required workflow."], ["How long does implementation take?", "Timing depends on scope, integrations and data migration. After the workflow review, we define a focused first version and a practical delivery plan."]];
const problemIcons = [IconScatter, IconAlert, IconRoute, IconClipboard];
const featureIcons = [IconLayers, IconKanban, IconUsers, IconClipboard, IconCoins, IconChart];
const workflow = [["Leads", IconRoute], ["Projects", IconKanban], ["Teams", IconUsers], ["Tasks", IconClipboard], ["Costs", IconCoins], ["Reports", IconChart]];
const directorViews = [
  ["Every project. One screen.", "See live stages, ownership, deadlines and the work that needs your attention — without chasing updates.", "PROJECT PORTFOLIO", IconKanban],
  ["See team performance at a glance.", "Know who is working where, which crews are overloaded and which actions are still open.", "CREWS & OPERATIONS", IconUsers],
  ["Know what your marketing is creating.", "Connect campaigns, enquiries and sales activity so advertising is part of the commercial picture.", "LEADS & CAMPAIGNS", IconMegaphone],
  ["Control plant, stock and costs.", "Bring equipment, materials, commitments and project cost information into the decisions that affect margin.", "RESOURCES & COSTS", IconBox],
  ["Open the report before the meeting.", "Give leadership one current view of revenue, performance and the exceptions that need a decision.", "DIRECTOR REPORTING", IconChart],
];

const ProductVisual = ({ src, alt }: { src: string; alt: string }) => <figure className="construction-product"><div className="product-bar"><i /><i /><i /><span>OPSYNQ / Construction OS</span><b>REAL PRODUCT</b></div><Image src={src} width={2200} height={1206} sizes="(max-width: 900px) 100vw, 55vw" alt={alt} /></figure>;

export default function ConstructionLandingPage() {
  return <main className="construction-landing">
    <ConstructionTracking />
    <header className="site-header construction-header"><nav className="nav shell" aria-label="Landing page navigation"><Brand /><div className="nav-links"><a href="#how-it-works">How It Works</a><a href="#product">Product</a><a href="#faq">FAQ</a></div><a className="nav-cta" href="#review" data-cta="workflow-review" data-location="nav">Free Workflow Review <span>↗</span></a></nav></header>
    <section className="construction-shell landing-hero"><div><span className="construction-kicker">BUILT FOR CONSTRUCTION LEADERS</span><h1><span className="hero-title-desktop">Still running your construction business through spreadsheets, WhatsApp and disconnected tools?</span><span className="hero-title-mobile">Run your construction business from <em>one clear system.</em></span></h1><p><span className="hero-copy-desktop">OPSYNQ builds one operating system around the way your company actually works — connecting projects, teams, leads, tasks, costs and reporting in one place.</span><span className="hero-copy-mobile">Projects. Crews. Costs. Reporting. Connected around the way you work.</span></p><div className="hero-actions"><a className="gold-button" href="#review" data-cta="workflow-review" data-location="hero">Get a Free Workflow Review <span>↗</span></a><a href="#how-it-works">See How It Works ↓</a></div><div className="hero-reassurance"><span>✓ A focused conversation about your operation</span><span>✓ No budget form. No generic sales pitch.</span></div></div><div className="hero-product"><span className="hero-product-label">REAL OPSYNQ CONSTRUCTION OS</span><ProductVisual src="/product/construction-dashboard.jpg" alt="OPSYNQ construction dashboard showing projects, crews, costs and performance" /></div></section>

    <aside className="decision-strip"><div className="construction-shell"><p>Built for owners, managing directors and operations leaders who need a clearer view of the business.</p><div><span>Leads & sales</span><span>Delivery & crews</span><span>Costs & control</span></div></div></aside>

    <section className="director-control"><div className="construction-shell"><div className="director-intro"><div><span className="construction-kicker">THE DIRECTOR&apos;S CONTROL CENTRE</span><h2>Stop asking for updates.<br /><em>See the business move.</em></h2></div><div><p>OPSYNQ gives you the views that matter when you run a construction company. Not five logins. Not a weekly spreadsheet. One system built around the decisions only you can make.</p><a className="gold-button" href="#review" data-cta="workflow-review" data-location="director-control">Get a Free Workflow Review <span>↗</span></a></div></div><div className="director-views">{directorViews.map(([title, text, label, Icon], index) => <article key={title} className={index === 0 ? "director-featured" : ""}><div className="icon-orb"><Icon /></div><span>{label}</span><h3>{title}</h3><p>{text}</p><i>↗</i></article>)}</div></div></section>

    <section className="landing-light"><div className="construction-shell"><div className="landing-heading"><span>THE PROBLEM</span><h2>Your business has outgrown disconnected tools.</h2></div><div className="problem-cards">{problems.map(([title, text], i) => { const Icon = problemIcons[i]; return <article key={title}><div className="icon-orb"><Icon /></div><b>0{i + 1}</b><h3>{title}</h3><p>{text}</p></article>; })}</div><div className="section-cta"><p>Bring the tools and handoffs that slow you down. We&apos;ll help identify the first process worth fixing.</p><a className="dark-button" href="#review" data-cta="workflow-review" data-location="problem">Get a Free Workflow Review <span>↗</span></a></div></div></section>
    <section className="solution-section" id="how-it-works"><div className="construction-shell split-heading"><div><span className="construction-kicker">ONE CONNECTED SYSTEM</span><h2>One operating system for your construction business.</h2></div><p>OPSYNQ connects the parts of your business that normally live in separate tools. Built around your workflow — not the other way around.</p></div><div className="construction-shell system-map">{workflow.map(([item, Icon], i) => <article key={item}><span>0{i + 1}</span><div className="icon-orb"><Icon /></div><b>{item}</b></article>)}</div><div className="construction-shell product-breakout"><ProductVisual src="/product/construction-teams.jpg" alt="OPSYNQ construction team and project operations interface" /></div></section>
    <section className="landing-light" id="product"><div className="construction-shell"><div className="landing-heading"><span>PRODUCT CAPABILITIES</span><h2>Control your business from one place.</h2></div><div className="feature-grid">{features.map(([title, text], i) => { const Icon = featureIcons[i]; return <article key={title}><div className="icon-orb"><Icon /></div><b>0{i + 1}</b><h3>{title}</h3><p>{text}</p></article>; })}</div><a className="dark-button" href="#review" data-cta="workflow-review" data-location="capabilities">Get a Free Workflow Review <span>↗</span></a></div></section>
    <section className="difference-section"><div className="construction-shell split-heading"><div><span className="construction-kicker">BUILT TO FIT</span><h2>Your business isn&apos;t generic. Your software shouldn&apos;t be either.</h2></div><p>Most software forces your company to change the way it works. OPSYNQ is built around your existing processes, team structure and operational needs.</p></div><div className="construction-shell comparison"><article><span>GENERIC SOFTWARE</span>{["Fixed workflows", "Unnecessary features", "Multiple disconnected apps", "Business adapts to software"].map(x => <p key={x}>× {x}</p>)}</article><article className="opsynq-column"><span>OPSYNQ</span>{["Built around your workflow", "Only the modules you need", "One connected system", "Software adapts to your business"].map(x => <p key={x}>✓ {x}</p>)}</article></div></section>
    <section className="start-section" id="process"><div className="construction-shell"><div className="landing-heading"><span>START SMALL</span><h2>You don&apos;t need to rebuild your entire company on day one.</h2><p>Start with one operational bottleneck. Build the first useful version. Expand the system as your company needs more.</p></div><div className="three-steps">{[["Identify the bottleneck", "We review how your business works today.", IconShield], ["Build the first solution", "We create the core system around the most valuable workflow.", IconLayers], ["Expand when needed", "Add automation, reporting and additional processes over time.", IconChart]].map(([title, text, Icon], i) => <article key={title}><div className="icon-orb"><Icon /></div><b>{i + 1}</b><h3>{title}</h3><p>{text}</p></article>)}</div><a className="dark-button start-cta" href="#review" data-cta="workflow-review" data-location="start-small">Get a Free Workflow Review <span>↗</span></a></div></section>
    <section className="review-process"><div className="construction-shell split-heading"><div><span className="construction-kicker">FREE WORKFLOW REVIEW</span><h2>See what OPSYNQ could look like for your company.</h2></div><p>No obligation. A short conversation focused on your actual business processes — so you can decide whether a tailored system is the right next step.</p></div><div className="construction-shell review-steps">{["Tell us what's slowing your business down.", "We review your current workflow and tools.", "Leave with a clear view of the first process a connected system could improve."].map((x, i) => <article key={x}><b>0{i + 1}</b><p>{x}</p></article>)}</div></section>
    <section className="form-section" id="review"><div className="construction-shell form-layout"><div><span className="construction-kicker">YOUR NEXT STEP</span><h2>Get a Free Workflow Review.</h2><p>Tell us about the bottleneck. We&apos;ll focus the conversation on your actual operation — not a generic software pitch.</p><div className="form-points"><span>✓ Tell us the problem in under a minute</span><span>✓ Get a practical first-step perspective</span><span>✓ No budget question or obligation</span></div><small className="form-note">For owners, managing directors and operations leaders.</small></div><WorkflowReviewForm /></div></section>
    <section className="faq-section-construction" id="faq"><div className="construction-shell faq-layout"><div><span className="construction-kicker">FAQ</span><h2>Useful answers before we talk.</h2></div><div>{faqs.map(([q, a], i) => <details key={q} open={i === 0}><summary><span>0{i + 1}</span>{q}<i>+</i></summary><p>{a}</p></details>)}</div></div></section>
    <section className="final-construction-cta"><div className="construction-shell"><div><span className="construction-kicker">ONE BUSINESS. ONE SYSTEM.</span><h2>Ready to run your construction business from one system?</h2><p>Let&apos;s identify the processes costing your company time and control — and show you what a better workflow could look like.</p><a className="gold-button" href="#review" data-cta="workflow-review" data-location="final">Get a Free Workflow Review</a></div><ProductVisual src="/product/subcontractors.jpg" alt="OPSYNQ subcontractor management interface" /></div></section>
    <footer className="construction-footer"><div className="construction-shell"><span>© 2026 OPSYNQ OS</span><div><Link href="/privacy">Privacy</Link><Link href="/cookies">Cookies</Link><Link href="/legal">Legal</Link></div></div></footer>
    <a className="mobile-sticky-cta" href="#review" data-cta="workflow-review" data-location="mobile-sticky">Get a Free Workflow Review</a>
  </main>;
}
