"""Derive the responsive image set used by the landing page.

Reads assets/img/src/*.jpg (originals), writes optimised JPEG + WebP
variants to assets/img/ and prints an LQIP map for assets/js/lqip.js.
"""
import base64, io, json, os
from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "img", "src")
OUT = os.path.join(ROOT, "assets", "img")

# name -> (source file, crop box as fractions l,t,r,b)
PLAN = {
    "hero-lake":       ("raw06.jpg", None),
    "exterior-spa":    ("raw01.jpg", None),
    "exterior-olive":  ("raw04.jpg", None),
    "exterior-forest": ("raw07.jpg", (0.012, 0.02, 0.988, 0.775)),   # trims the watermark strip
    "village":         ("raw08.jpg", None),
    "village-wide":    ("raw10.jpg", None),
    "interior-loft":   ("raw02.jpg", None),
    "interior-kitchen":("raw02.jpg", (0.0, 0.14, 0.66, 0.86)),  # drops the mirrored panel
    "interior-stairs": ("raw05.jpg", None),
    "interior-bath":   ("raw03.jpg", None),
    "terrace":         ("raw09.jpg", None),
}

WIDTHS = [480, 800, 1280, 1536, 1920]

def variants(name, img):
    made = []
    for w in WIDTHS:
        if w > img.width * 1.02:
            continue
        h = round(img.height * w / img.width)
        r = img.resize((w, h), Image.LANCZOS)
        r.save(os.path.join(OUT, f"{name}-{w}.jpg"), "JPEG",
               quality=80, optimize=True, progressive=True)
        r.save(os.path.join(OUT, f"{name}-{w}.webp"), "WEBP", quality=74, method=6)
        made.append(w)
    return made

def lqip(img):
    t = img.resize((22, max(1, round(22 * img.height / img.width))), Image.LANCZOS)
    t = t.filter(ImageFilter.GaussianBlur(0.6))
    buf = io.BytesIO()
    t.save(buf, "JPEG", quality=42)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()

manifest = {}
for name, (fname, box) in PLAN.items():
    img = Image.open(os.path.join(SRC, fname)).convert("RGB")
    if box:
        l, t, r, b = box
        img = img.crop((round(l * img.width), round(t * img.height),
                        round(r * img.width), round(b * img.height)))
    made = variants(name, img)
    manifest[name] = {"w": img.width, "h": img.height, "sizes": made, "lqip": lqip(img)}
    print(f"{name:16} {img.width}x{img.height}  ->  {made}")

with open(os.path.join(ROOT, "assets", "js", "lqip.js"), "w") as f:
    f.write("/* Generated by scripts/build-images.py — do not edit by hand. */\n")
    f.write("window.ARKHAUS_LQIP = " + json.dumps(
        {k: v["lqip"] for k, v in manifest.items()}, indent=0) + ";\n")

print("\ntotal output:",
      sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT)
          if os.path.isfile(os.path.join(OUT, f))) // 1024, "KB")
