import type { Metadata } from "next";
import { notFound } from "next/navigation";

type Locale = "nl" | "da" | "no" | "sv" | "ie";

const content = {
  nl: { lang:"nl-NL", country:"Nederland", eyebrow:"MAATWERK SOFTWARE VOOR GROEIENDE BEDRIJVEN", title:"Uw volledige bedrijf. Eén intelligent systeem.", intro:"Wij ontwerpen Business Operating Systems op maat die CRM, medewerkers, processen, financiën, documenten, advertenties en AI samenbrengen in één platform.", cta:"Plan een gratis strategiesessie", min:"Projecten vanaf €5.000", why:"Geen standaardpakket. Een oplossing die precies past bij uw bedrijf.", body:"Bent u Excel, losse CRM-systemen of handmatig werk ontgroeid? Wij analyseren hoe uw organisatie werkelijk functioneert en bouwen vervolgens één veilige, schaalbare omgeving voor directie en teams. Google Ads, Meta/Facebook, spreadsheets, bestaande databases en bedrijfssystemen worden onderdeel van dezelfde informatiestroom.", services:"Wat wij automatiseren", items:["CRM en verkoop","Medewerkers en activiteiten","Projecten en operations","Financiën en facturatie","Documenten en goedkeuringen","Google- en Facebook-advertenties","Excel en databases","AI-assistenten en rapportage"], close:"Klaar voor volledige controle over uw bedrijf?", closeText:"Vertel ons wat u wilt verbeteren. U krijgt een eerlijk technisch en commercieel advies—zonder standaard verkooppresentatie."},
  da: { lang:"da-DK", country:"Danmark", eyebrow:"SKRÆDDERSYET SOFTWARE TIL VIRKSOMHEDER I VÆKST", title:"Hele din virksomhed. Ét intelligent system.", intro:"Vi designer skræddersyede Business Operating Systems, der samler CRM, medarbejdere, drift, økonomi, dokumenter, annoncering og AI på én platform.", cta:"Book en gratis strategisamtale", min:"Projekter fra €5.000", why:"Ikke en standardplatform. En løsning bygget præcist til jeres forretning.", body:"Når Excel og adskilte systemer bremser virksomheden, skaber vi én sikker og skalerbar arbejdsplatform. Ledelsen får det fulde overblik, mens hver medarbejder får de rette data, opgaver og automatiseringer. Google Ads, Meta/Facebook, regneark, egne databaser og eksisterende systemer forbindes i samme flow.", services:"Det automatiserer vi", items:["CRM og salg","Medarbejdere og aktivitet","Projekter og drift","Økonomi og fakturering","Dokumenter og godkendelser","Google- og Facebook-annoncer","Excel og databaser","AI-assistenter og rapportering"], close:"Klar til fuld kontrol over virksomheden?", closeText:"Fortæl os, hvad I vil forbedre. I får en klar teknisk og kommerciel retning—uden en generisk salgspræsentation."},
  no: { lang:"nb-NO", country:"Norge", eyebrow:"SKREDDERSYDD PROGRAMVARE FOR BEDRIFTER I VEKST", title:"Hele virksomheten. Ett intelligent system.", intro:"Vi utvikler skreddersydde Business Operating Systems som samler CRM, ansatte, drift, økonomi, dokumenter, annonsering og AI på én plattform.", cta:"Bestill en gratis strategisamtale", min:"Prosjekter fra €5 000", why:"Ikke en standardplattform. En løsning bygget nøyaktig for deres virksomhet.", body:"Når Excel og frakoblede systemer bremser veksten, bygger vi én sikker og skalerbar arbeidsplattform. Ledelsen får full oversikt, og hver medarbeider får riktige data, oppgaver og automatiseringer. Google Ads, Meta/Facebook, regneark, egne databaser og eksisterende systemer kobles sammen i én informasjonsflyt.", services:"Dette automatiserer vi", items:["CRM og salg","Ansatte og aktivitet","Prosjekter og drift","Økonomi og fakturering","Dokumenter og godkjenninger","Google- og Facebook-annonser","Excel og databaser","AI-assistenter og rapportering"], close:"Klar for full kontroll over virksomheten?", closeText:"Fortell oss hva dere vil forbedre. Dere får tydelige tekniske og kommersielle råd—uten en generisk salgspresentasjon."},
  sv: { lang:"sv-SE", country:"Sverige", eyebrow:"SKRÄDDARSYDD PROGRAMVARA FÖR VÄXANDE FÖRETAG", title:"Hela verksamheten. Ett intelligent system.", intro:"Vi utvecklar skräddarsydda Business Operating Systems som samlar CRM, medarbetare, drift, ekonomi, dokument, annonsering och AI på en plattform.", cta:"Boka ett kostnadsfritt strategisamtal", min:"Projekt från €5 000", why:"Ingen standardplattform. En lösning byggd exakt för er verksamhet.", body:"När Excel och frånkopplade system bromsar tillväxten bygger vi en säker och skalbar arbetsplattform. Ledningen får full överblick och varje medarbetare får rätt data, uppgifter och automatiseringar. Google Ads, Meta/Facebook, kalkylblad, egna databaser och befintliga system kopplas samman i samma informationsflöde.", services:"Det här automatiserar vi", items:["CRM och försäljning","Medarbetare och aktivitet","Projekt och drift","Ekonomi och fakturering","Dokument och godkännanden","Google- och Facebook-annonser","Excel och databaser","AI-assistenter och rapportering"], close:"Redo för full kontroll över verksamheten?", closeText:"Berätta vad ni vill förbättra. Ni får en tydlig teknisk och kommersiell riktning—utan en generisk säljpresentation."},
  ie: { lang:"en-IE", country:"Ireland", eyebrow:"CUSTOM BUSINESS SOFTWARE FOR GROWING COMPANIES", title:"Your entire business. One intelligent system.", intro:"We build custom Business Operating Systems that unite CRM, employees, operations, finance, documents, advertising, and AI in one platform.", cta:"Book a free strategy call", min:"Projects from €5,000", why:"Not an off-the-shelf platform. A solution designed precisely for your business.", body:"When spreadsheets and disconnected tools begin limiting growth, we create one secure, scalable operating environment. Leadership gains complete visibility while every employee receives the right data, tasks, and automations. Google Ads, Meta/Facebook, Excel, private databases, and existing systems become part of one reliable information flow.", services:"What we automate", items:["CRM and sales","Employees and activity","Projects and operations","Finance and invoicing","Documents and approvals","Google and Facebook advertising","Excel and databases","AI assistants and reporting"], close:"Ready for complete control of your business?", closeText:"Tell us what you want to improve. You will receive clear technical and commercial direction—without a generic sales presentation."}
} satisfies Record<Locale, {lang:string;country:string;eyebrow:string;title:string;intro:string;cta:string;min:string;why:string;body:string;services:string;items:string[];close:string;closeText:string}>;

export function generateStaticParams(){ return Object.keys(content).map(locale=>({locale})); }

export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{
  const {locale} = await params;
  const c = content[locale as Locale];
  if(!c) return {};
  return { title:`Custom Business Software in ${c.country}`, description:c.intro, alternates:{canonical:`/${locale}`,languages:{"en":"/","en-IE":"/ie","nl-NL":"/nl","da-DK":"/da","nb-NO":"/no","sv-SE":"/sv","x-default":"/"}}, openGraph:{title:c.title,description:c.intro,locale:c.lang.replace("-","_")} };
}

export default async function LocalizedPage({params}:{params:Promise<{locale:string}>}){
  const {locale} = await params;
  const c = content[locale as Locale];
  if(!c) notFound();
  return <main className="locale-page">
    <nav className="nav shell"><a className="brand" href="/"><span className="brand-mark">N</span>NORTH<span>/OS</span></a><div className="locale-nav"><a href="/">EN</a><a href="/nl">NL</a><a href="/da">DA</a><a href="/no">NO</a><a href="/sv">SV</a><a href="/ie">IE</a></div><a className="nav-cta" href="/#contact">{c.cta} <span>↗</span></a></nav>
    <section className="locale-hero shell"><div className="eyebrow"><i/> {c.eyebrow}</div><h1>{c.title}</h1><p>{c.intro}</p><div className="actions"><a className="button primary" href="/#contact">{c.cta} <span>↗</span></a><span className="locale-price">{c.min}</span></div><div className="locale-orbit" aria-hidden="true"><b>CRM</b><b>AI</b><b>ERP</b><b>ADS</b><i>ONE<br/>SYSTEM</i></div></section>
    <section className="locale-proof"><div className="shell"><div className="kicker">NORTH/OS / {c.country.toUpperCase()}</div><h2>{c.why}</h2><p>{c.body}</p></div></section>
    <section className="locale-services shell"><div><div className="kicker">CONNECTED BY DESIGN</div><h2>{c.services}</h2></div><div>{c.items.map((x,i)=><article key={x}><span>0{i+1}</span><b>{x}</b><i>✓</i></article>)}</div></section>
    <section className="locale-cta"><div className="shell"><h2>{c.close}</h2><p>{c.closeText}</p><a className="button primary" href="/#contact">{c.cta} <span>↗</span></a><small>{c.min}</small></div></section>
    <footer><div className="shell footer-bottom"><span>© 2026 NORTH/OS</span><span>{c.country} · Working globally</span><a href="/">English version ↗</a></div></footer>
  </main>;
}
