import type { Metadata } from "next";
import { notFound } from "next/navigation";

type Locale = "nl"|"da"|"no"|"sv"|"ie";
const markets = {
  nl:{country:"Netherlands",demonym:"Dutch",city:"Amsterdam",focus:"business automation software and custom CRM development"},
  da:{country:"Denmark",demonym:"Danish",city:"Copenhagen",focus:"workflow automation and internal business software"},
  no:{country:"Norway",demonym:"Norwegian",city:"Oslo",focus:"operations management software and custom ERP"},
  sv:{country:"Sweden",demonym:"Swedish",city:"Stockholm",focus:"business process automation and AI business automation"},
  ie:{country:"Ireland",demonym:"Irish",city:"Dublin",focus:"custom business software and business operating systems"},
} satisfies Record<Locale,{country:string;demonym:string;city:string;focus:string}>;

export function generateStaticParams(){return Object.keys(markets).map(locale=>({locale}));}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;const m=markets[locale as Locale];if(!m)return{};return{title:`Business Automation Software in ${m.country} | NORTH/OS`,description:`Business Operating Systems for growing ${m.demonym} companies. Custom CRM, workflow automation, ERP connections and AI automation from €5,000.`,keywords:[`business automation software ${m.country}`,`custom business software ${m.country}`,`custom CRM development ${m.country}`,`business operating system ${m.country}`,m.focus],alternates:{canonical:`/${locale}`,languages:{"en":"/","en-NL":"/nl","en-DK":"/da","en-NO":"/no","en-SE":"/sv","en-IE":"/ie","x-default":"/"}}};}

export default async function MarketPage({params}:{params:Promise<{locale:string}>}){const {locale}=await params;const m=markets[locale as Locale];if(!m)notFound();const schema={"@context":"https://schema.org","@type":"Service","name":`Business Automation Software for Companies in ${m.country}`,"provider":{"@type":"Organization","name":"NORTH/OS"},"areaServed":{"@type":"Country","name":m.country},"serviceType":["Business Operating System","Custom CRM Development","Workflow Automation","Custom ERP","AI Business Automation"],"offers":{"@type":"Offer","price":"5000","priceCurrency":"EUR","description":"Core Business Operating System implementation starting from €5,000"}};return <main>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <nav className="topbar wrap"><a className="logo" href="/"><span>N</span>NORTH<i>/OS</i></a><div className="navlinks"><a href="/#platform">Platform</a><a href="/#packages">Packages</a><a href="/#solutions">Solutions</a></div><a className="navbutton" href="/#contact">Configure your system <b>↗</b></a></nav>
  <section className="market-hero wrap"><div className="overline"><span/> BUSINESS OPERATING SYSTEMS · {m.country.toUpperCase()}</div><h1>Business automation software for <em>{m.demonym} companies.</em></h1><p>Replace disconnected systems, Excel spreadsheets and manual administration with one modular Business Operating System—configured around your workflows, teams and growth plans.</p><div className="hero-actions"><a className="btn blue" href="/#contact">Book strategy call <b>↗</b></a><a className="btn outline" href="/#packages">Packages from €5,000 <b>↘</b></a></div><div className="market-proof"><span>For CEOs & Managing Directors</span><span>English-language implementation</span><span>{m.city} · Remote delivery across {m.country}</span></div></section>
  <section className="market-value"><div className="wrap"><div><div className="section-label">COMMERCIAL OUTCOME</div><h2>One operational platform.<br/><em>Fewer systems to manage.</em></h2></div><div><p>NORTH/OS connects CRM, projects, employees, finance, documents, reporting and automation. Leadership gets real-time operational visibility while teams work from one reliable source of truth.</p><p>Start with Core, add Automation, then expand into industry modules, ERP connections, AI agents and multi-company control.</p></div></div></section>
  <section className="market-services wrap"><div className="section-heading"><div><div className="section-label">HIGH-VALUE BUSINESS SOFTWARE</div><h2>Configured for how<br/><em>your company operates.</em></h2></div><p>Built for growing companies that have outgrown generic CRM, spreadsheets and fragmented SaaS subscriptions.</p></div><div className="market-grid">{[["Custom CRM development","Customers, sales pipelines, quotations and account activity."],["Workflow automation","Approvals, notifications, documents and repetitive operational work."],["Custom ERP & integrations","Accounting, inventory, production and existing enterprise systems."],["Operations management software","Projects, tasks, employees, roles, deadlines and performance."],["AI business automation","Context-aware assistants, reporting and controlled AI agents."],["Industry operating systems","Construction, manufacturing, distribution, logistics and property."]].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
  <section className="market-cta"><div className="wrap"><div><div className="section-label">NORTH/OS · {m.country.toUpperCase()}</div><h2>Ready to replace manual work?</h2><p>Discuss your systems, workflows and growth plans with a Business Automation Studio—not a website agency.</p></div><a className="btn blue" href="/#contact">Configure your NORTH/OS <b>↗</b></a></div></section>
  <footer><div className="wrap footer-bottom"><span>© 2026 NORTH/OS</span><span>Serving companies across {m.country}</span><a href="/">Global website ↗</a></div></footer>
  </main>}
